name: NiceAuth
version: '${project.version}'
main: it.skrahs.niceauth.NiceAuth
commands:
  auth:
    aliases:
      - a
      - authlogin
      - authregister
      - loginauth
      - registerauth
  register:
  login:
  Changepassword:
    aliases:
      - chp
      - changepass
      - changepassw
      - cpassw
      - changep


